# Generated by Django 3.0.3 on 2020-08-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_map', '0003_auto_20200803_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Restaurants',
        ),
    ]
