# Generated by Django 3.0.3 on 2020-08-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_map', '0004_auto_20200803_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
    ]
