# Generated by Django 3.0.3 on 2020-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_map', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='grade',
            field=models.IntegerField(),
        ),
    ]
