# Generated by Django 3.0.3 on 2020-08-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_map', '0007_auto_20200803_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
